-- MySQL Script generated by MySQL Workbench
-- Sat May  4 12:42:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BDoptica
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BDoptica` ;

-- -----------------------------------------------------
-- Schema BDoptica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BDoptica` DEFAULT CHARACTER SET utf8 ;
USE `BDoptica` ;

-- -----------------------------------------------------
-- Table `BDoptica`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDoptica`.`proveedor` (
  `cod_proveedor` INT(15) NOT NULL AUTO_INCREMENT,
  `nif` VARCHAR(9) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `piso` VARCHAR(10) NULL,
  `puerta` VARCHAR(10) NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `codigo_postal` INT(5) NOT NULL,
  `pais` VARCHAR(20) NOT NULL,
  `telefono` VARCHAR(12) NOT NULL,
  `fax` VARCHAR(12) NULL,
  PRIMARY KEY (`cod_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDoptica`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDoptica`.`producto` (
  `cod_producto` INT(15) NOT NULL AUTO_INCREMENT,
  `cod_proveedor` INT(15) NOT NULL,
  `marca` VARCHAR(20) NOT NULL,
  `graduacion_der` VARCHAR(5) NOT NULL,
  `graduacion_izq` VARCHAR(5) NOT NULL,
  `montura` VARCHAR(10) NOT NULL,
  `color_montura` VARCHAR(10) NOT NULL,
  `color_vidrio` VARCHAR(10) NOT NULL,
  `precio` DOUBLE NOT NULL,
  PRIMARY KEY (`cod_producto`),
  CONSTRAINT `cod_proveedor`
    FOREIGN KEY (`cod_proveedor`)
    REFERENCES `BDoptica`.`proveedor` (`cod_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `cod_proveedor_idx` ON `BDoptica`.`producto` (`cod_proveedor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `BDoptica`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDoptica`.`cliente` (
  `cod_cliente` INT(45) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido1` VARCHAR(45) NOT NULL,
  `apellido2` VARCHAR(45) NULL,
  `telefono` VARCHAR(12) NULL,
  `fecha_registro` DATE NOT NULL,
  `cod_cliente_recomedacion` INT(15) NULL,
  PRIMARY KEY (`cod_cliente`),
  CONSTRAINT `cod_cliente_recomendacion`
    FOREIGN KEY (`cod_cliente_recomedacion`)
    REFERENCES `BDoptica`.`cliente` (`cod_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `cod_cliente_recomendacion_idx` ON `BDoptica`.`cliente` (`cod_cliente_recomedacion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `BDoptica`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDoptica`.`empleado` (
  `cod_empleado` INT(20) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido1` VARCHAR(45) NOT NULL,
  `apellido2` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDoptica`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDoptica`.`venta` (
  `cod_venta` INT(45) NOT NULL AUTO_INCREMENT,
  `cod_cliente` INT(45) NOT NULL,
  `cod_empleado` INT(20) NOT NULL,
  `cod_producto` INT(15) NOT NULL,
  `cantidad` INT(100) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `cod_producto` DATE NOT NULL,
  PRIMARY KEY (`cod_venta`),
  CONSTRAINT `cod_cliente`
    FOREIGN KEY (`cod_cliente`)
    REFERENCES `BDoptica`.`cliente` (`cod_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cod_empleado`
    FOREIGN KEY (`cod_empleado`)
    REFERENCES `BDoptica`.`empleado` (`cod_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cod_producto`
    FOREIGN KEY (`cod_producto`)
    REFERENCES `BDoptica`.`producto` (`cod_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `cod_cliente_idx` ON `BDoptica`.`venta` (`cod_cliente` ASC) VISIBLE;

CREATE INDEX `cod_empleado_idx` ON `BDoptica`.`venta` (`cod_empleado` ASC) VISIBLE;

CREATE INDEX `cod_producto_idx` ON `BDoptica`.`venta` (`cod_producto` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
